# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: deprecation

# The name of the component, or a single word describing the area of concern, (e.g. otlpreceiver)
component: config

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Deprecate all types and funcs in `config` package

# One or more tracking issues or pull requests related to the change
issues: [6422]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  - config.ComponentID => component.ID
  - config.Type => component.Type
  - config.DataType => component.DataType
  - config.Receiver => component.ReceiverConfig
  - config.UnmarshalReceiver => component.UnmarshalReceiverConfig
  - config.[New]ReceiverSettings => component.[New]ReceiverConfigSettings
  - config.Processor => component.ProcessorConfig
  - config.UnmarshalProcessor => component.UnmarshalProcessorConfig
  - config.[New]ProcessorSettings => component.[New]ProcessorConfigSettings
  - config.Exporter => component.ExporterConfig
  - config.UnmarshalExporter => component.UnmarshalExporterConfig
  - config.[New]ExporterSettings => component.[New]ExporterConfigSettings
  - config.Extension => component.ExtensionConfig
  - config.UnmarshalExtension => component.UnmarshalExtensionConfig
  - config.[New]ExtensionSettings => component.[New]ExtensionConfigSettings
